### ISSUE TITLE
line numbers render not lined up

### ISSUE THREAD

**Issue by CarlFK** [SymbiFlow/sphinxcontrib-hdl-diagrams#64]
on this page, line numbers don't land where they should:
Firefox, 79.0 Unbutu 

https://sphinxcontrib-hdl-diagrams.readthedocs.io/en/latest/examples/comb-full-adder.html

![Screenshot from 2020-09-24 18-53-51](https://user-images.githubusercontent.com/23225/94211618-8b5f0b00-fe97-11ea-978c-acd4d4a493e5.png)

**Comment by daniellimws** [comment]
Fixed in https://github.com/SymbiFlow/sphinx_symbiflow_theme/pull/44
